sudo: required
language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - pip install pytest==4.5.0 pytest-cov pylint flask pytest-flask
  - docker build -t alexfeig/bluegreen .
  - docker run -d -p 5000:5000 alexfeig/bluegreen

script:
  - pytest --cov=bluegreen/ --cov-report=term