sudo: required
language: python

services:
  - docker

before_install:
  - pip install pytest pytest-cov pylint
  - docker build -t alexfeig/bluegreen .
  - docker run -d -p 5000:5000 bluegreen

script:
  - pytest